<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [11]:
import numpy as np

In [9]:
numbers=[-1,3,5,9,12]

In [10]:
np_array_numbers= np.array(numbers)
np_array_numbers

array([-1,  3,  5,  9, 12])

In [8]:
np_array_numbers * 10

array([ -1.,  30.,  50.,  90., 120.])

In [21]:
numbers1 = {13,.12,-0.11}

In [22]:
np_array_numbers1 = np.array(numbers1)
np_array_numbers1

array({0.12, 13, -0.11}, dtype=object)

### Difference between Python and Numpy Data Structures

In [24]:
numbers * 5

[-1,
 3,
 5,
 9,
 12,
 -1,
 3,
 5,
 9,
 12,
 -1,
 3,
 5,
 9,
 12,
 -1,
 3,
 5,
 9,
 12,
 -1,
 3,
 5,
 9,
 12]

In [26]:
np_array_numbers * 5

array([-5, 15, 25, 45, 60])