<h1>Boolean Mask Arrays</h1>

In [10]:
import numpy as np

In [11]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [14]:
divisible_by_7 = 0==(my_vector%7)
divisible_by_7

array([False, False,  True, False,  True, False,  True])

In [13]:
num_divisible_by_7 = my_vector[divisible_by_7]
num_divisible_by_7

array([  0,  21, 105])

In [16]:
num_divisible_by_7[num_divisible_by_7>0]

array([ 21, 105])

### Method 2, using combined mask with logical_and() func

In [17]:
more_than_zero = my_vector > 0
more_than_zero

array([False, False, False,  True,  True,  True,  True])

In [18]:
combined_mask = np.logical_and(more_than_zero,divisible_by_7)

In [19]:
my_vector[combined_mask]

array([ 21, 105])