<h1>Broadcasting</h1>

In [2]:
import numpy as np

In [3]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [6]:
my_3D_array.shape ### returns shape attribute of array

(2, 7, 5)

In [8]:
my_3D_array.ndim ### returns dimension attributeof array

3

In [10]:
my_3D_array.size ### returns size attribute of array

70

In [11]:
my_3D_array.dtype ### returns data type attribute of array

dtype('int32')

In [12]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [13]:
my_3D_array.sum() #sum up the entire array

2415

In [15]:
my_3D_array.sum(axis=0) #sum up 2D arrays within 3D array

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [17]:
my_3D_array.sum(axis=1) #sum up rows within 3D array

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [19]:
my_3D_array.sum(axis=2) #sum up columns within 3D array

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [20]:
my_2D_array = np.ones(49,dtype="int_").reshape((7,5)) * 3
my_2D_array

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [28]:
my_random_2D_array = np.random.random((7,5)) ### returns random floats in half-open intervals [0,1)
my_random_2D_array

array([[0.5598, 0.4019, 0.5555, 0.1208, 0.3147],
       [0.8453, 0.4855, 0.0345, 0.6149, 0.6702],
       [0.8581, 0.4322, 0.1721, 0.1607, 0.9768],
       [0.2848, 0.2555, 0.285 , 0.1387, 0.8832],
       [0.3016, 0.5297, 0.0966, 0.5109, 0.2232],
       [0.3396, 0.4281, 0.5528, 0.56  , 0.4753],
       [0.0283, 0.5911, 0.147 , 0.5823, 0.3617]])

In [27]:
np.set_printoptions(precision=4) 
print(my_3D_array)
my_3D_array * my_random_2D_array

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]


array([[[ 0.    ,  0.7729,  0.377 ,  0.8343,  1.2202],
        [ 3.1428,  2.3575,  6.3702,  4.0124,  4.9398],
        [ 4.5293,  3.3496,  5.303 ,  7.4606,  4.3337],
        [ 9.979 , 14.2824, 16.111 ,  2.0309,  8.558 ],
        [19.184 , 14.6859, 19.7579, 18.5313, 19.3488],
        [ 8.0284,  1.8782, 26.7023, 10.5494,  7.2884],
        [24.0786, 28.5439,  7.7677,  7.0904, 21.6145]],

       [[33.8566, 27.8227,  6.9737, 10.5676, 11.897 ],
        [25.1426, 16.1096, 38.2213, 21.5665, 24.1499],
        [20.382 , 14.0073, 20.7701, 27.5468, 15.1678],
        [33.2632, 45.5252, 49.2807,  5.9798, 24.3229],
        [52.756 , 39.1624, 51.191 , 46.731 , 47.5658],
        [19.2681,  4.4066, 61.3165, 23.7362, 16.0847],
        [52.1703, 60.7709, 16.2637, 14.6105, 43.8648]]])