<h2>Intrinsic NumPy array creation using NumPy's methods</h2>

In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(5,25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [4]:
np.arange(5,25,5)

array([ 5, 10, 15, 20])

In [5]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

### Methods to check size of numpy array

In [7]:
np.arange(5,26)-5+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [8]:
np.arange(5,26,5).size


5

### arange without start value

In [9]:
np.arange(46,step=5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])