<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [2]:
import numpy as np

### linspace()

In [3]:
np.linspace(9,15,16)

array([ 9. ,  9.4,  9.8, 10.2, 10.6, 11. , 11.4, 11.8, 12.2, 12.6, 13. ,
       13.4, 13.8, 14.2, 14.6, 15. ])

##### linspace uses closed interval (end parameter included in array)

In [4]:
np.linspace(9,15,16,retstep=True)

(array([ 9. ,  9.4,  9.8, 10.2, 10.6, 11. , 11.4, 11.8, 12.2, 12.6, 13. ,
        13.4, 13.8, 14.2, 14.6, 15. ]),
 0.4)

### zeros()

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### ones()

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### 2D, 3D arrays

In [13]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### Change data type in array

### Default data type for zeros(), ones(): float

In [15]:
np.zeros(5,dtype="int64")

array([0, 0, 0, 0, 0], dtype=int64)

In [16]:
np.ones((4,4), dtype="int64")


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)